github.com/titpetric/exp/cmd/go-fsck/internal/telemetry
github.com/titpetric/exp/cmd/go-fsck/model
github.com/titpetric/exp/cmd/go-fsck/internal
github.com/titpetric/exp/cmd/go-fsck/internal/ast
github.com/titpetric/exp/cmd/go-fsck/internal/collector
github.com/titpetric/exp/cmd/go-fsck/model/loader
github.com/titpetric/exp/cmd/go-fsck/coverage
github.com/titpetric/exp/cmd/go-fsck/docs
github.com/titpetric/exp/cmd/go-fsck/extract
github.com/titpetric/exp/cmd/go-fsck/lint
github.com/titpetric/exp/cmd/go-fsck/query
github.com/titpetric/exp/cmd/go-fsck/report/testusage
github.com/titpetric/exp/cmd/go-fsck/report
github.com/titpetric/exp/cmd/go-fsck/internal/files
github.com/titpetric/exp/cmd/go-fsck/restore
github.com/titpetric/exp/cmd/go-fsck/search
github.com/titpetric/exp/cmd/go-fsck/stats/modules
github.com/titpetric/exp/cmd/go-fsck/stats
github.com/titpetric/exp/cmd/go-fsck
github.com/titpetric/exp/cmd/go-fsck/example
github.com/titpetric/exp/cmd/go-fsck/model/restored
github.com/titpetric/exp/cmd/go-fsck/sqlite
@startuml
' Have 22 definitions
' Have 5 declarations in github.com/titpetric/exp/cmd/go-fsck/internal/telemetry

' Have 60 declarations in github.com/titpetric/exp/cmd/go-fsck/model

' Have 7 declarations in github.com/titpetric/exp/cmd/go-fsck/internal

' Have 7 declarations in github.com/titpetric/exp/cmd/go-fsck/internal/ast

' Have 22 declarations in github.com/titpetric/exp/cmd/go-fsck/internal/collector

' Have 3 declarations in github.com/titpetric/exp/cmd/go-fsck/model/loader

' Have 11 declarations in github.com/titpetric/exp/cmd/go-fsck/coverage

' Have 12 declarations in github.com/titpetric/exp/cmd/go-fsck/docs

' Have 9 declarations in github.com/titpetric/exp/cmd/go-fsck/extract

' Have 6 declarations in github.com/titpetric/exp/cmd/go-fsck/lint

' Have 6 declarations in github.com/titpetric/exp/cmd/go-fsck/query

' Have 8 declarations in github.com/titpetric/exp/cmd/go-fsck/report/testusage

' Have 6 declarations in github.com/titpetric/exp/cmd/go-fsck/report

' Have 2 declarations in github.com/titpetric/exp/cmd/go-fsck/internal/files

' Have 18 declarations in github.com/titpetric/exp/cmd/go-fsck/restore

' Have 6 declarations in github.com/titpetric/exp/cmd/go-fsck/search

' Have 25 declarations in github.com/titpetric/exp/cmd/go-fsck/stats/modules

' Have 8 declarations in github.com/titpetric/exp/cmd/go-fsck/stats

' Have 2 declarations in github.com/titpetric/exp/cmd/go-fsck

' Have 13 declarations in github.com/titpetric/exp/cmd/go-fsck/example

' Have 60 declarations in github.com/titpetric/exp/cmd/go-fsck/model/restored

' Have 5 declarations in github.com/titpetric/exp/cmd/go-fsck/sqlite

[github.com/titpetric/exp/cmd/go-fsck] --|> [github.com/titpetric/exp/cmd/go-fsck/lint]
[github.com/titpetric/exp/cmd/go-fsck] --|> [github.com/titpetric/exp/cmd/go-fsck/coverage]
[github.com/titpetric/exp/cmd/go-fsck] --|> [github.com/titpetric/exp/cmd/go-fsck/extract]
[github.com/titpetric/exp/cmd/go-fsck] --|> [github.com/titpetric/exp/cmd/go-fsck/stats]
[github.com/titpetric/exp/cmd/go-fsck] --|> [github.com/titpetric/exp/cmd/go-fsck/docs]
[github.com/titpetric/exp/cmd/go-fsck] --|> [github.com/titpetric/exp/cmd/go-fsck/search]
[github.com/titpetric/exp/cmd/go-fsck] --|> [github.com/titpetric/exp/cmd/go-fsck/query]
[github.com/titpetric/exp/cmd/go-fsck] --|> [github.com/titpetric/exp/cmd/go-fsck/report]
[github.com/titpetric/exp/cmd/go-fsck] --|> [github.com/titpetric/exp/cmd/go-fsck/restore]
[github.com/titpetric/exp/cmd/go-fsck/coverage] --|> [github.com/titpetric/exp/cmd/go-fsck/model/loader]
[github.com/titpetric/exp/cmd/go-fsck/coverage] --|> [github.com/titpetric/exp/cmd/go-fsck/internal]
[github.com/titpetric/exp/cmd/go-fsck/coverage] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/docs] --|> [github.com/titpetric/exp/cmd/go-fsck/model/loader]
[github.com/titpetric/exp/cmd/go-fsck/docs] --|> [github.com/titpetric/exp/cmd/go-fsck/internal]
[github.com/titpetric/exp/cmd/go-fsck/docs] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/extract] --|> [github.com/titpetric/exp/cmd/go-fsck/internal/telemetry]
[github.com/titpetric/exp/cmd/go-fsck/extract] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/extract] --|> [github.com/titpetric/exp/cmd/go-fsck/internal]
[github.com/titpetric/exp/cmd/go-fsck/extract] --|> [github.com/titpetric/exp/cmd/go-fsck/model/loader]
[github.com/titpetric/exp/cmd/go-fsck/internal] --|> [github.com/titpetric/exp/cmd/go-fsck/internal/telemetry]
[github.com/titpetric/exp/cmd/go-fsck/internal] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/internal/collector] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/internal/collector] --|> [github.com/titpetric/exp/cmd/go-fsck/internal/ast]
[github.com/titpetric/exp/cmd/go-fsck/lint] --|> [github.com/titpetric/exp/cmd/go-fsck/internal]
[github.com/titpetric/exp/cmd/go-fsck/lint] --|> [github.com/titpetric/exp/cmd/go-fsck/model/loader]
[github.com/titpetric/exp/cmd/go-fsck/lint] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/model/loader] --|> [github.com/titpetric/exp/cmd/go-fsck/internal/collector]
[github.com/titpetric/exp/cmd/go-fsck/model/loader] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/query] --|> [github.com/titpetric/exp/cmd/go-fsck/internal]
[github.com/titpetric/exp/cmd/go-fsck/query] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/query] --|> [github.com/titpetric/exp/cmd/go-fsck/model/loader]
[github.com/titpetric/exp/cmd/go-fsck/report] --|> [github.com/titpetric/exp/cmd/go-fsck/internal]
[github.com/titpetric/exp/cmd/go-fsck/report] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/report] --|> [github.com/titpetric/exp/cmd/go-fsck/model/loader]
[github.com/titpetric/exp/cmd/go-fsck/report] --|> [github.com/titpetric/exp/cmd/go-fsck/report/testusage]
[github.com/titpetric/exp/cmd/go-fsck/report/testusage] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/restore] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/restore] --|> [github.com/titpetric/exp/cmd/go-fsck/model/loader]
[github.com/titpetric/exp/cmd/go-fsck/restore] --|> [github.com/titpetric/exp/cmd/go-fsck/internal/files]
[github.com/titpetric/exp/cmd/go-fsck/search] --|> [github.com/titpetric/exp/cmd/go-fsck/internal]
[github.com/titpetric/exp/cmd/go-fsck/search] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/search] --|> [github.com/titpetric/exp/cmd/go-fsck/model/loader]
[github.com/titpetric/exp/cmd/go-fsck/sqlite] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/stats] --|> [github.com/titpetric/exp/cmd/go-fsck/internal]
[github.com/titpetric/exp/cmd/go-fsck/stats] --|> [github.com/titpetric/exp/cmd/go-fsck/model/loader]
[github.com/titpetric/exp/cmd/go-fsck/stats] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
[github.com/titpetric/exp/cmd/go-fsck/stats] --|> [github.com/titpetric/exp/cmd/go-fsck/stats/modules]
[github.com/titpetric/exp/cmd/go-fsck/stats/modules] --|> [github.com/titpetric/exp/cmd/go-fsck/model]
@enduml
