@startuml

class Allocator {
  - pool: sync.Pool
}

class Body {
  + Name: string
}

class File {
  - type: string
}

class Reseter {
  - type: any
}

class logger {
  - out: []string
}


note top of Allocator
Allocator holds a sync.Pool of objects of type T.
end note



note top of Body
Body represends a decoded body
end note



note top of File
File represents a filename
end note



note top of Reseter
Reseter is the interface that types must implement to be managed by Allocator.
end note




@enduml
