@startuml

class "example.Allocator[T Reseter]" {
  - pool: sync.Pool
}

class "example.Body" {
  + Name: string
}

interface "example.Reseter" {
  + Reset: Reset ()
}

class "example.logger" {
  - out: []string
  + Log (s string)
}






@enduml
