@startuml

class Complexity {
  + Cognitive: int
  + Cyclomatic: int
  + Lines: int
  + Coverage: float64
}

class Declaration {
  + Kind: DeclarationKind
  + Type: string
  + File: string
  + Line: int
  + SelfContained: bool
  + Imports: []string
  + References: StringSet
  + Globals: StringSet
  + Doc: string
  + Name: string
  + Names: []string
  + Receiver: string
  + Fields: FieldList
  + Arguments: []string
  + Returns: []string
  + Signature: string
  + Source: string
  + Complexity: *Complexity
}

class DeclarationKind {
  - type: string
  + String () string
}

class DeclarationList {
  - type: []*Declaration
  + Exported () DeclarationList
  + Filter (matchfn func(d *Declaration) bool) DeclarationList
  + Find (matchfn func(d *Declaration) bool) *Declaration
  + Walk (matchfn func(d *Declaration))
}

class Definition {
  + Doc: string
  + Imports: StringSet
  + InitCount: int
  + Types: DeclarationList
  + Consts: DeclarationList
  + Vars: DeclarationList
  + Funcs: DeclarationList
}

class DefinitionList {
  - type: []*Definition
  + Filter (matchfn func(d *Definition) bool) []*Definition
  + Find (matchfn func(d *Definition) bool) *Definition
  + Walk (matchfn func(d *Definition))
}

class Field {
  + Name: string
  + Type: string
  + Path: string
  + Doc: string
  + Comment: string
  + Tag: string
  + JSONName: string
  + MapKey: string
}

class FieldList {
  - type: []*Field
}

class Package {
  + ID: string
  + Package: string
  + ImportPath: string
  + Path: string
  + TestPackage: bool
  + Complexity: *Complexity
  + Pkg: *packages.Package
  + Equal (in Package) bool
  + Name () string
  + String () string
}

class StringSet {
  - type: map[string][]string
  + All () []string
  + Get (key string) []string
  + Map (imports []string) (map[string]string, []error)
}


Declaration --> DeclarationKind : Kind
Declaration --> StringSet : References
Declaration --> StringSet : Globals
Declaration --> FieldList : Fields
Declaration --> Complexity : Complexity

note top of Declaration
Declaration holds information about a go symbol.
end note



note top of DeclarationKind
DeclarationKind is an enum of go symbol types.
end note


DeclarationList --> Declaration : type

note top of DeclarationList
DeclarationList holds a list of Go symbols.
end note


DeclarationList --> DeclarationList : Exported()
DeclarationList --> DeclarationList : Filter()
DeclarationList --> Declaration : Find()
Package --|> Definition : embeded by
Definition --> StringSet : Imports
Definition --> DeclarationList : Types
Definition --> DeclarationList : Consts
Definition --> DeclarationList : Vars
Definition --> DeclarationList : Funcs

note top of Definition
Definition holds all symbols defined for a Package.
end note


DefinitionList --> Definition : type

note top of DefinitionList
DefinitionList holds a list of Go packages.
end note


DefinitionList --> Definition : Filter()
DefinitionList --> Definition : Find()

note top of Field
Field holds details about a field definition.
end note


FieldList --> Field : type

note top of FieldList
FieldList contains all struct fields.
end note


Package --> Complexity : Complexity

note top of Package
Package holds go package information.
end note



note top of StringSet
StringSet provides a key based unique string slice.
end note



@enduml
