package model

var BuiltInTypes = map[string]bool{
	"string":      true,
	"int":         true,
	"int8":        true,
	"int16":       true,
	"int32":       true,
	"int64":       true,
	"uint":        true,
	"uint8":       true,
	"uint16":      true,
	"uint32":      true,
	"uint64":      true,
	"uintptr":     true,
	"float32":     true,
	"float64":     true,
	"complex64":   true,
	"complex128":  true,
	"byte":        true,
	"rune":        true,
	"bool":        true,
	"error":       true,
	"interface{}": true,
}
